apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatroom-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: custom-class
  hostPath:
    path: "/mnt/data"